/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FeeDialog.java
 *
 * Created on Jan 6, 2011, 9:06:24 AM
 */

package view;

import model.LibImages;

/**
 *
 * @author CuongNQ
 */
public class FeeDialog extends javax.swing.JDialog {

    /** Creates new form FeeDialog */
    public FeeDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FeePal = new javax.swing.JPanel();
        lblDayFee = new javax.swing.JLabel();
        lblLateFee = new javax.swing.JLabel();
        btnChange = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtDayFee = new javax.swing.JFormattedTextField();
        txtLateFee = new javax.swing.JFormattedTextField();
        lblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        FeePal.setBorder(javax.swing.BorderFactory.createTitledBorder("Fee Information"));

        lblDayFee.setText("Day Fee:");

        lblLateFee.setText("Late Fee:");

        btnChange.setText("Change");

        btnCancel.setText("Cancel");

        txtDayFee.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        txtLateFee.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        org.jdesktop.layout.GroupLayout FeePalLayout = new org.jdesktop.layout.GroupLayout(FeePal);
        FeePal.setLayout(FeePalLayout);
        FeePalLayout.setHorizontalGroup(
            FeePalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(FeePalLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(FeePalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, FeePalLayout.createSequentialGroup()
                        .add(FeePalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblDayFee)
                            .add(lblLateFee))
                        .add(18, 18, 18)
                        .add(FeePalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(txtLateFee, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .add(txtDayFee, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, FeePalLayout.createSequentialGroup()
                        .add(btnChange)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(btnCancel)))
                .addContainerGap())
        );
        FeePalLayout.setVerticalGroup(
            FeePalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(FeePalLayout.createSequentialGroup()
                .addContainerGap()
                .add(FeePalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblDayFee)
                    .add(txtDayFee, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(FeePalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblLateFee)
                    .add(txtLateFee, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(FeePalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(btnCancel)
                    .add(btnChange))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(LibImages.LABEL_FEERATE)));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(lblImage)
                .add(18, 18, 18)
                .add(FeePal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(lblImage)
                        .add(29, 29, 29))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(FeePal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FeeDialog dialog = new FeeDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FeePal;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChange;
    private javax.swing.JLabel lblDayFee;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLateFee;
    private javax.swing.JFormattedTextField txtDayFee;
    private javax.swing.JFormattedTextField txtLateFee;
    // End of variables declaration//GEN-END:variables

}
