/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginFrm.java
 *
 * Created on Jan 1, 2011, 2:29:26 PM
 */
package view;

import javax.swing.ImageIcon;
import model.LibImages;

/**
 *
 * @author CuongNQ
 */
public class LoginFrm extends javax.swing.JFrame {

    /** Creates new form LoginFrm */
    public LoginFrm() {
        initComponents();
        //Set this frame to center of monitor
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAbout = new javax.swing.JLabel();
        lblLoginIcon = new javax.swing.JLabel();
        panelLogin = new javax.swing.JPanel();
        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        chBxRemember = new javax.swing.JCheckBox();
        btnLogin = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        mnSystem = new javax.swing.JMenu();
        menuSetting = new javax.swing.JMenuItem();
        separator = new javax.swing.JPopupMenu.Separator();
        mnQuit = new javax.swing.JMenuItem();
        mnHelp = new javax.swing.JMenu();
        mnSubHelp = new javax.swing.JMenuItem();
        mnAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setResizable(false);

        lblAbout.setFont(new java.awt.Font("Lucida Grande", 2, 12));
        lblAbout.setText("Powered by Group-01.GC0502 - Vr1.0");

        lblLoginIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource(LibImages.Label_Login)));

        panelLogin.setBorder(javax.swing.BorderFactory.createTitledBorder("Login Information"));

        lblUserName.setText("Username:");

        lblPassword.setText("Password:");

        txtUsername.setToolTipText("Your user name");

        txtPassword.setToolTipText("Your password");

        chBxRemember.setText("Remember me");
        chBxRemember.setToolTipText("Check it if you want remember login information for next time");

        btnLogin.setText("Login");

        org.jdesktop.layout.GroupLayout panelLoginLayout = new org.jdesktop.layout.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, panelLoginLayout.createSequentialGroup()
                .add(21, 21, 21)
                .add(panelLoginLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(panelLoginLayout.createSequentialGroup()
                        .add(panelLoginLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblUserName)
                            .add(lblPassword))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(panelLoginLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(txtUsername, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .add(txtPassword, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)))
                    .add(panelLoginLayout.createSequentialGroup()
                        .add(chBxRemember)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 106, Short.MAX_VALUE)
                        .add(btnLogin)))
                .addContainerGap())
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelLoginLayout.createSequentialGroup()
                .add(9, 9, 9)
                .add(panelLoginLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblUserName)
                    .add(txtUsername, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelLoginLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblPassword)
                    .add(txtPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelLoginLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(chBxRemember)
                    .add(btnLogin))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mnSystem.setText("System");

        menuSetting.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        menuSetting.setIcon(new ImageIcon(getClass().getResource(LibImages.Menu_Setting)));
        menuSetting.setText("Setting");
        mnSystem.add(menuSetting);
        mnSystem.add(separator);

        mnQuit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        mnQuit.setIcon(new ImageIcon(getClass().getResource(LibImages.Menu_Quit)));
        mnQuit.setText("Quit");
        mnSystem.add(mnQuit);

        menuBar.add(mnSystem);

        mnHelp.setText("Help");

        mnSubHelp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        mnSubHelp.setText("Help");
        mnHelp.add(mnSubHelp);

        mnAbout.setIcon(new ImageIcon(getClass().getResource(LibImages.Menu_About)));
        mnAbout.setText("About us");
        mnHelp.add(mnAbout);

        menuBar.add(mnHelp);

        setJMenuBar(menuBar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(lblLoginIcon, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblAbout)
                    .add(panelLogin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(panelLogin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(16, 16, 16)
                .add(lblAbout))
            .add(layout.createSequentialGroup()
                .add(4, 4, 4)
                .add(lblLoginIcon, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox chBxRemember;
    private javax.swing.JLabel lblAbout;
    private javax.swing.JLabel lblLoginIcon;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuSetting;
    private javax.swing.JMenuItem mnAbout;
    private javax.swing.JMenu mnHelp;
    private javax.swing.JMenuItem mnQuit;
    private javax.swing.JMenuItem mnSubHelp;
    private javax.swing.JMenu mnSystem;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPopupMenu.Separator separator;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the chBxRemember
     */
    public javax.swing.JCheckBox getChBxRemember() {
        return chBxRemember;
    }

    /**
     * @param chBxRemember the chBxRemember to set
     */
    public void setChBxRemember(javax.swing.JCheckBox chBxRemember) {
        this.chBxRemember = chBxRemember;
    }

    /**
     * @return the menuSetting
     */
    public javax.swing.JMenuItem getMenuSetting() {
        return menuSetting;
    }

    /**
     * @param menuSetting the menuSetting to set
     */
    public void setMenuSetting(javax.swing.JMenuItem menuSetting) {
        this.menuSetting = menuSetting;
    }

    /**
     * @return the mnAbout
     */
    public javax.swing.JMenuItem getMnAbout() {
        return mnAbout;
    }

    /**
     * @param mnAbout the mnAbout to set
     */
    public void setMnAbout(javax.swing.JMenuItem mnAbout) {
        this.mnAbout = mnAbout;
    }

    /**
     * @return the mnQuit
     */
    public javax.swing.JMenuItem getMnQuit() {
        return mnQuit;
    }

    /**
     * @param mnQuit the mnQuit to set
     */
    public void setMnQuit(javax.swing.JMenuItem mnQuit) {
        this.mnQuit = mnQuit;
    }

    /**
     * @return the btnLogin
     */
    public javax.swing.JButton getBtnLogin() {
        return btnLogin;
    }

    /**
     * @param btnLogin the btnLogin to set
     */
    public void setBtnLogin(javax.swing.JButton btnLogin) {
        this.btnLogin = btnLogin;
    }

    /**
     * @return the lblUserName
     */
    public javax.swing.JLabel getLblUserName() {
        return lblUserName;
    }

    /**
     * @param lblUserName the lblUserName to set
     */
    public void setLblUserName(javax.swing.JLabel lblUserName) {
        this.lblUserName = lblUserName;
    }

    /**
     * @return the txtPassword
     */
    public javax.swing.JPasswordField getTxtPassword() {
        return txtPassword;
    }

    /**
     * @param txtPassword the txtPassword to set
     */
    public void setTxtPassword(javax.swing.JPasswordField txtPassword) {
        this.txtPassword = txtPassword;
    }

    /**
     * @return the txtUsername
     */
    public javax.swing.JTextField getTxtUsername() {
        return txtUsername;
    }

    /**
     * @param txtUsername the txtUsername to set
     */
    public void setTxtUsername(javax.swing.JTextField txtUsername) {
        this.txtUsername = txtUsername;
    }

    /**
     * @return the mnSubHelp
     */
    public javax.swing.JMenuItem getMnSubHelp() {
        return mnSubHelp;
    }

    /**
     * @param mnSubHelp the mnSubHelp to set
     */
    public void setMnSubHelp(javax.swing.JMenuItem mnSubHelp) {
        this.mnSubHelp = mnSubHelp;
    }
}
