/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * manageFrm.java
 *
 * Created on Dec 31, 2010, 1:32:10 PM
 */
package view;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import model.LibImages;

/**
 *
 * @author CuongNQ
 */
public class ManageFrm extends javax.swing.JFrame {


    /** Creates new form manageFrm */
    public ManageFrm() {
        //All component
        initComponents();
        //Set this frame to center of monitor
        setLocationRelativeTo(null);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        taskPalManage = new org.jdesktop.swingx.JXTaskPane();
        btnEmpMan = new JButton();
        btnBookMan = new JButton();
        btnSubMan = new JButton();
        taskPalBorAna = new org.jdesktop.swingx.JXTaskPane();
        btnBorMan = new JButton();
        btnAnaMan = new JButton();
        palMain = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        mnSystem = new javax.swing.JMenu();
        menuSetting = new javax.swing.JMenuItem();
        separator = new javax.swing.JPopupMenu.Separator();
        mnLogout = new javax.swing.JMenuItem();
        mnQuit = new javax.swing.JMenuItem();
        mnEmp = new javax.swing.JMenu();
        mnBook = new javax.swing.JMenu();
        mnSub = new javax.swing.JMenu();
        mnBor = new javax.swing.JMenu();
        mnAna = new javax.swing.JMenu();
        mnHelp = new javax.swing.JMenu();
        mnSubHelp = new javax.swing.JMenuItem();
        mnAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management System");
        setMinimumSize(new java.awt.Dimension(700, 360));
        setName("manageFrm"); // NOI18N

        taskPalManage.setTitle("Management");
        taskPalManage.setFocusable(false);

        btnEmpMan.setIcon(new ImageIcon(getClass().getResource(LibImages.TASKBAR_EMPLOYEE)));
        btnEmpMan.setMnemonic('e');
        btnEmpMan.setText("Employee");
        btnEmpMan.setBorderPainted(false);
        btnEmpMan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        taskPalManage.getContentPane().add(btnEmpMan);

        btnBookMan.setIcon(new ImageIcon(getClass().getResource(LibImages.TASKBAR_BOOK)));
        btnBookMan.setMnemonic('b');
        btnBookMan.setText("Book");
        btnBookMan.setBorderPainted(false);
        btnBookMan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        taskPalManage.getContentPane().add(btnBookMan);

        btnSubMan.setIcon(new ImageIcon(getClass().getResource(LibImages.TASKBAR_SUB)));
        btnSubMan.setMnemonic('u');
        btnSubMan.setText("Subject");
        btnSubMan.setBorderPainted(false);
        btnSubMan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        taskPalManage.getContentPane().add(btnSubMan);

        taskPalBorAna.setTitle("Borrow & Analytic");
        taskPalBorAna.setFocusable(false);
        //Set font for all button menu
        btnEmpMan.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        btnBookMan.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        btnSubMan.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        btnBorMan.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        btnAnaMan.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N

        btnBorMan.setIcon(new ImageIcon(getClass().getResource(LibImages.TASKBAR_BORROW)));
        btnBorMan.setMnemonic('r');
        btnBorMan.setText("Borrow");
        btnBorMan.setBorderPainted(false);
        btnBorMan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        taskPalBorAna.getContentPane().add(btnBorMan);

        btnAnaMan.setIcon(new ImageIcon(getClass().getResource(LibImages.TASKBAR_ANALYTIC)));
        btnAnaMan.setMnemonic('n');
        btnAnaMan.setText("Analytic");
        btnAnaMan.setBorderPainted(false);
        btnAnaMan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        taskPalBorAna.getContentPane().add(btnAnaMan);

        palMain.setLayout(new java.awt.CardLayout());

        mnSystem.setMnemonic('m');
        mnSystem.setText("System");

        menuSetting.setIcon(new ImageIcon(getClass().getResource(LibImages.MENU_SETTING)));
        menuSetting.setText("Setting");
        mnSystem.add(menuSetting);
        mnSystem.add(separator);

        mnLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        mnLogout.setIcon(new ImageIcon(getClass().getResource(LibImages.MENU_LOGOUT)));
        mnLogout.setText("Logout");
        mnSystem.add(mnLogout);

        mnQuit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        mnQuit.setIcon(new ImageIcon(getClass().getResource(LibImages.MENU_QUIT)));
        mnQuit.setText("Quit");
        mnSystem.add(mnQuit);

        menuBar.add(mnSystem);

        mnEmp.setMnemonic('e');
        mnEmp.setText("Employee");
        menuBar.add(mnEmp);

        mnBook.setMnemonic('b');
        mnBook.setText("Book");
        menuBar.add(mnBook);

        mnSub.setMnemonic('u');
        mnSub.setText("Subject");
        menuBar.add(mnSub);

        mnBor.setMnemonic('r');
        mnBor.setText("Borrow");
        menuBar.add(mnBor);

        mnAna.setMnemonic('n');
        mnAna.setText("Analytic");
        menuBar.add(mnAna);

        mnHelp.setMnemonic('p');
        mnHelp.setText("Help");

        mnSubHelp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        mnSubHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource(LibImages.MENU_HELP)));
        mnSubHelp.setText("Help");
        mnHelp.add(mnSubHelp);

        mnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource(LibImages.MENU_ABOUT)));
        mnAbout.setText("About us");
        mnHelp.add(mnAbout);

        menuBar.add(mnHelp);

        setJMenuBar(menuBar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, taskPalManage, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, taskPalBorAna, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(palMain, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(palMain, 0, 0, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(taskPalManage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(taskPalBorAna, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnaMan;
    private javax.swing.JButton btnBookMan;
    private javax.swing.JButton btnBorMan;
    private javax.swing.JButton btnEmpMan;
    private javax.swing.JButton btnSubMan;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuSetting;
    private javax.swing.JMenuItem mnAbout;
    private javax.swing.JMenu mnAna;
    private javax.swing.JMenu mnBook;
    private javax.swing.JMenu mnBor;
    private javax.swing.JMenu mnEmp;
    private javax.swing.JMenu mnHelp;
    private javax.swing.JMenuItem mnLogout;
    private javax.swing.JMenuItem mnQuit;
    private javax.swing.JMenu mnSub;
    private javax.swing.JMenuItem mnSubHelp;
    private javax.swing.JMenu mnSystem;
    private javax.swing.JPanel palMain;
    private javax.swing.JPopupMenu.Separator separator;
    private org.jdesktop.swingx.JXTaskPane taskPalBorAna;
    private org.jdesktop.swingx.JXTaskPane taskPalManage;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the palMain
     */
    public javax.swing.JPanel getPalMain() {
        return palMain;
    }

    /**
     * @param palMain the palMain to set
     */
    public void setPalMain(javax.swing.JPanel palMain) {
        this.palMain = palMain;
    }

    /**
     * @return the btnBookMan
     */
    public javax.swing.JButton getBtnBookMan() {
        return btnBookMan;
    }

    /**
     * @param btnBookMan the btnBookMan to set
     */
    public void setBtnBookMan(javax.swing.JButton btnBookMan) {
        this.btnBookMan = btnBookMan;
    }

    /**
     * @return the btnAnaMan
     */
    public javax.swing.JButton getBtnAnaMan() {
        return btnAnaMan;
    }

    /**
     * @param btnAnaMan the btnAnaMan to set
     */
    public void setBtnAnaMan(javax.swing.JButton btnAnaMan) {
        this.btnAnaMan = btnAnaMan;
    }

    /**
     * @return the btnBorMan
     */
    public javax.swing.JButton getBtnBorMan() {
        return btnBorMan;
    }

    /**
     * @param btnBorMan the btnBorMan to set
     */
    public void setBtnBorMan(javax.swing.JButton btnBorMan) {
        this.btnBorMan = btnBorMan;
    }

    /**
     * @return the btnEmpMan
     */
    public javax.swing.JButton getBtnEmpMan() {
        return btnEmpMan;
    }

    /**
     * @param btnEmpMan the btnEmpMan to set
     */
    public void setBtnEmpMan(javax.swing.JButton btnEmpMan) {
        this.btnEmpMan = btnEmpMan;
    }

    /**
     * @return the btnSubMan
     */
    public javax.swing.JButton getBtnSubMan() {
        return btnSubMan;
    }

    /**
     * @param btnSubMan the btnSubMan to set
     */
    public void setBtnSubMan(javax.swing.JButton btnSubMan) {
        this.btnSubMan = btnSubMan;
    }

    /**
     * @return the mnAbout
     */
    public javax.swing.JMenuItem getMnAbout() {
        return mnAbout;
    }

    /**
     * @param mnAbout the mnAbout to set
     */
    public void setMnAbout(javax.swing.JMenuItem mnAbout) {
        this.mnAbout = mnAbout;
    }

    /**
     * @return the mnLogout
     */
    public javax.swing.JMenuItem getMnLogout() {
        return mnLogout;
    }

    /**
     * @param mnLogout the mnLogout to set
     */
    public void setMnLogout(javax.swing.JMenuItem mnLogout) {
        this.mnLogout = mnLogout;
    }

    /**
     * @return the mnQuit
     */
    public javax.swing.JMenuItem getMnQuit() {
        return mnQuit;
    }

    /**
     * @param mnQuit the mnQuit to set
     */
    public void setMnQuit(javax.swing.JMenuItem mnQuit) {
        this.mnQuit = mnQuit;
    }

    /**
     * @return the menuSetting
     */
    public javax.swing.JMenuItem getMenuSetting() {
        return menuSetting;
    }

    /**
     * @param menuSetting the menuSetting to set
     */
    public void setMenuSetting(javax.swing.JMenuItem menuSetting) {
        this.menuSetting = menuSetting;
    }

    /**
     * @return the mnAna
     */
    public javax.swing.JMenu getMnAna() {
        return mnAna;
    }

    /**
     * @param mnAna the mnAna to set
     */
    public void setMnAna(javax.swing.JMenu mnAna) {
        this.mnAna = mnAna;
    }

    /**
     * @return the mnBook
     */
    public javax.swing.JMenu getMnBook() {
        return mnBook;
    }

    /**
     * @param mnBook the mnBook to set
     */
    public void setMnBook(javax.swing.JMenu mnBook) {
        this.mnBook = mnBook;
    }

    /**
     * @return the mnBor
     */
    public javax.swing.JMenu getMnBor() {
        return mnBor;
    }

    /**
     * @param mnBor the mnBor to set
     */
    public void setMnBor(javax.swing.JMenu mnBor) {
        this.mnBor = mnBor;
    }

    /**
     * @return the mnEmp
     */
    public javax.swing.JMenu getMnEmp() {
        return mnEmp;
    }

    /**
     * @param mnEmp the mnEmp to set
     */
    public void setMnEmp(javax.swing.JMenu mnEmp) {
        this.mnEmp = mnEmp;
    }

    /**
     * @return the mnSub
     */
    public javax.swing.JMenu getMnSub() {
        return mnSub;
    }

    /**
     * @param mnSub the mnSub to set
     */
    public void setMnSub(javax.swing.JMenu mnSub) {
        this.mnSub = mnSub;
    }
}
