/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PalBorrow.java
 *
 * Created on Jan 3, 2011, 6:03:25 PM
 */

package view;

import model.LibImages;

/**
 *
 * @author CuongNQ
 */
public class PalBorrow extends javax.swing.JPanel {

    /** Creates new form PalBorrow */
    public PalBorrow() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tolbarBor = new javax.swing.JToolBar();
        btnChkOut = new javax.swing.JButton();
        btnChkIn = new javax.swing.JButton();
        btnFee = new javax.swing.JButton();
        separator7 = new javax.swing.JToolBar.Separator();
        btnEditBor = new javax.swing.JButton();
        btnViewBor = new javax.swing.JButton();
        btnDelBor = new javax.swing.JButton();
        separator8 = new javax.swing.JToolBar.Separator();
        btnSearchBor = new javax.swing.JButton();
        scrPanBor = new javax.swing.JScrollPane();
        tblBor = new javax.swing.JTable();
        lblCallNoBor = new javax.swing.JLabel();
        lblEmNmBor = new javax.swing.JLabel();
        txtEmNamBor = new javax.swing.JTextField();
        txtCallNoBor = new javax.swing.JTextField();

        tolbarBor.setBorder(null);
        tolbarBor.setFloatable(false);
        tolbarBor.setBorderPainted(false);
        tolbarBor.setOpaque(false);

        btnChkOut.setIcon(new javax.swing.ImageIcon(getClass().getResource(LibImages.Taskbar_CheckOut)));
        btnChkOut.setMnemonic('o');
        btnChkOut.setText("Check-Out");
        btnChkOut.setBorderPainted(false);
        btnChkOut.setFocusable(false);
        btnChkOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChkOut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tolbarBor.add(btnChkOut);

        btnChkIn.setIcon(new javax.swing.ImageIcon(getClass().getResource(LibImages.Taskbar_CheckIn)));
        btnChkIn.setMnemonic('i');
        btnChkIn.setText("Check-In");
        btnChkIn.setBorderPainted(false);
        btnChkIn.setFocusable(false);
        btnChkIn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChkIn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tolbarBor.add(btnChkIn);

        btnFee.setIcon(new javax.swing.ImageIcon(getClass().getResource(LibImages.Taskbar_Fee)));
        btnFee.setMnemonic('f');
        btnFee.setText("Fee rate");
        btnFee.setBorderPainted(false);
        btnFee.setFocusable(false);
        btnFee.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFee.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tolbarBor.add(btnFee);
        tolbarBor.add(separator7);

        btnEditBor.setIcon(new javax.swing.ImageIcon(getClass().getResource(LibImages.Taskbar_Edit)));
        btnEditBor.setMnemonic('e');
        btnEditBor.setText("Edit");
        btnEditBor.setBorderPainted(false);
        btnEditBor.setEnabled(false);
        btnEditBor.setFocusable(false);
        btnEditBor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditBor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tolbarBor.add(btnEditBor);

        btnViewBor.setIcon(new javax.swing.ImageIcon(getClass().getResource(LibImages.Taskbar_View)));
        btnViewBor.setMnemonic('v');
        btnViewBor.setText("View");
        btnViewBor.setBorderPainted(false);
        btnViewBor.setEnabled(false);
        btnViewBor.setFocusable(false);
        btnViewBor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnViewBor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tolbarBor.add(btnViewBor);

        btnDelBor.setIcon(new javax.swing.ImageIcon(getClass().getResource(LibImages.Taskbar_Delete)));
        btnDelBor.setMnemonic('d');
        btnDelBor.setText("Delete");
        btnDelBor.setBorderPainted(false);
        btnDelBor.setEnabled(false);
        btnDelBor.setFocusable(false);
        btnDelBor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelBor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tolbarBor.add(btnDelBor);
        tolbarBor.add(separator8);

        btnSearchBor.setIcon(new javax.swing.ImageIcon(getClass().getResource(LibImages.Taskbar_Search)));
        btnSearchBor.setMnemonic('s');
        btnSearchBor.setText("Search");
        btnSearchBor.setBorderPainted(false);
        btnSearchBor.setFocusable(false);
        btnSearchBor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSearchBor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tolbarBor.add(btnSearchBor);

        tblBor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scrPanBor.setViewportView(tblBor);

        lblCallNoBor.setText("CallNo:");

        lblEmNmBor.setText("Emp Name:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 588, Short.MAX_VALUE)
            .add(scrPanBor, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(tolbarBor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblEmNmBor)
                    .add(lblCallNoBor))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(txtEmNamBor, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .add(txtCallNoBor, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 337, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, tolbarBor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lblCallNoBor)
                            .add(txtCallNoBor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(2, 2, 2)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lblEmNmBor)
                            .add(txtEmNamBor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(scrPanBor, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChkIn;
    private javax.swing.JButton btnChkOut;
    private javax.swing.JButton btnDelBor;
    private javax.swing.JButton btnEditBor;
    private javax.swing.JButton btnFee;
    private javax.swing.JButton btnSearchBor;
    private javax.swing.JButton btnViewBor;
    private javax.swing.JLabel lblCallNoBor;
    private javax.swing.JLabel lblEmNmBor;
    private javax.swing.JScrollPane scrPanBor;
    private javax.swing.JToolBar.Separator separator7;
    private javax.swing.JToolBar.Separator separator8;
    private javax.swing.JTable tblBor;
    private javax.swing.JToolBar tolbarBor;
    private javax.swing.JTextField txtCallNoBor;
    private javax.swing.JTextField txtEmNamBor;
    // End of variables declaration//GEN-END:variables

}
