/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProgramSettingDialog.java
 *
 * Created on Jan 9, 2011, 10:47:23 PM
 */
package view;

import java.util.Vector;
import model.LibImages;
import org.pushingpixels.substance.api.SubstanceLookAndFeel;
import org.pushingpixels.substance.api.skin.SkinInfo;

/**
 *
 * @author CuongNQ
 */
public class ProgramSettingDialog extends javax.swing.JDialog {

    /** Creates new form ProgramSettingDialog */
    public ProgramSettingDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        palSetting = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnDefault = new javax.swing.JButton();
        lblNoRow = new javax.swing.JLabel();
        lblTheme = new javax.swing.JLabel();
        txtRow = new javax.swing.JSpinner();
        cbxTheme = new javax.swing.JComboBox(new Vector<SkinInfo>(
            SubstanceLookAndFeel.getAllSkins().values()));
    btnClose = new javax.swing.JButton();
    lblImage = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Program Setting");
    setResizable(false);

    palSetting.setBorder(javax.swing.BorderFactory.createTitledBorder("Program Setting"));

    btnSave.setText("Save");

    btnDefault.setText("Default");

    lblNoRow.setText("No row a page:");

    lblTheme.setText("Themes:");

    txtRow.setValue(1);

    btnClose.setText("Close");

    org.jdesktop.layout.GroupLayout palSettingLayout = new org.jdesktop.layout.GroupLayout(palSetting);
    palSetting.setLayout(palSettingLayout);
    palSettingLayout.setHorizontalGroup(
        palSettingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(palSettingLayout.createSequentialGroup()
            .addContainerGap()
            .add(palSettingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(palSettingLayout.createSequentialGroup()
                    .add(btnSave)
                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                    .add(btnDefault)
                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                    .add(btnClose))
                .add(palSettingLayout.createSequentialGroup()
                    .add(palSettingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(lblTheme)
                        .add(lblNoRow))
                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                    .add(palSettingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(txtRow, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                        .add(cbxTheme, 0, 152, Short.MAX_VALUE))))
            .addContainerGap())
    );
    palSettingLayout.setVerticalGroup(
        palSettingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(org.jdesktop.layout.GroupLayout.TRAILING, palSettingLayout.createSequentialGroup()
            .addContainerGap()
            .add(palSettingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                .add(lblNoRow, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(txtRow, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(palSettingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                .add(cbxTheme, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(lblTheme))
            .add(18, 18, 18)
            .add(palSettingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                .add(btnClose)
                .add(btnDefault)
                .add(btnSave))
            .addContainerGap())
    );

    lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(LibImages.LABEL_SETTING)));

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(layout.createSequentialGroup()
            .addContainerGap()
            .add(lblImage, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .add(18, 18, 18)
            .add(palSetting, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(layout.createSequentialGroup()
            .addContainerGap()
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                .add(lblImage)
                .add(palSetting, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDefault;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cbxTheme;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblNoRow;
    private javax.swing.JLabel lblTheme;
    private javax.swing.JPanel palSetting;
    private javax.swing.JSpinner txtRow;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the btnClose
     */
    public javax.swing.JButton getBtnClose() {
        return btnClose;
    }

    /**
     * @param btnClose the btnClose to set
     */
    public void setBtnClose(javax.swing.JButton btnClose) {
        this.btnClose = btnClose;
    }

    /**
     * @return the btnDefault
     */
    public javax.swing.JButton getBtnDefault() {
        return btnDefault;
    }

    /**
     * @param btnDefault the btnDefault to set
     */
    public void setBtnDefault(javax.swing.JButton btnDefault) {
        this.btnDefault = btnDefault;
    }

    /**
     * @return the btnSave
     */
    public javax.swing.JButton getBtnSave() {
        return btnSave;
    }

    /**
     * @param btnSave the btnSave to set
     */
    public void setBtnSave(javax.swing.JButton btnSave) {
        this.btnSave = btnSave;
    }

    /**
     * @return the cbxTheme
     */
    public javax.swing.JComboBox getCbxTheme() {
        return cbxTheme;
    }

    /**
     * @param cbxTheme the cbxTheme to set
     */
    public void setCbxTheme(javax.swing.JComboBox cbxTheme) {
        this.cbxTheme = cbxTheme;
    }

    /**
     * @return the txtRow
     */
    public javax.swing.JSpinner getTxtRow() {
        return txtRow;
    }

    /**
     * @param txtRow the txtRow to set
     */
    public void setTxtRow(javax.swing.JSpinner txtRow) {
        this.txtRow = txtRow;
    }

}
