/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ViewBookDialog.java
 *
 * Created on Jan 4, 2011, 5:44:43 PM
 */

package view;

import model.LibImages;

/**
 *
 * @author CuongNQ
 */
public class ViewBookDialog extends javax.swing.JDialog {

    /** Creates new form ViewBookDialog */
    public ViewBookDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImage = new javax.swing.JLabel();
        bookInfoPal = new javax.swing.JPanel();
        lblCallNo = new javax.swing.JLabel();
        lblISBN = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblAth = new javax.swing.JLabel();
        lblPub = new javax.swing.JLabel();
        lblSub = new javax.swing.JLabel();
        lblNoC = new javax.swing.JLabel();
        lblNoInL = new javax.swing.JLabel();
        lblWho = new javax.swing.JLabel();
        lblCallNo1 = new javax.swing.JLabel();
        lblISBN1 = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblAth1 = new javax.swing.JLabel();
        lblPub1 = new javax.swing.JLabel();
        lblSub1 = new javax.swing.JLabel();
        lblNoC1 = new javax.swing.JLabel();
        lblNoInL1 = new javax.swing.JLabel();
        lblWho1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        scrPanBorBook = new javax.swing.JScrollPane();
        tblBor = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(774, 560));

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(LibImages.LABEL_INFOBOOK)));

        bookInfoPal.setBorder(javax.swing.BorderFactory.createTitledBorder("Book Information"));

        lblCallNo.setText("CallNumber:");

        lblISBN.setText("ISBN:");

        lblTitle.setText("Title:");

        lblAth.setText("Author:");

        lblPub.setText("Publisher:");

        lblSub.setText("Subject:");

        lblNoC.setText("No of copies:");

        lblNoInL.setText("No in library:");

        lblWho.setText("New borrowed by:");

        lblCallNo1.setText("Empty");

        lblISBN1.setText("Empty");

        lblTitle1.setText("Empty");

        lblAth1.setText("Empty");

        lblPub1.setText("Empty");

        lblSub1.setText("Empty");

        lblNoC1.setText("Empty");

        lblNoInL1.setText("Empty");

        lblWho1.setText("Empty");

        org.jdesktop.layout.GroupLayout bookInfoPalLayout = new org.jdesktop.layout.GroupLayout(bookInfoPal);
        bookInfoPal.setLayout(bookInfoPalLayout);
        bookInfoPalLayout.setHorizontalGroup(
            bookInfoPalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(bookInfoPalLayout.createSequentialGroup()
                .addContainerGap()
                .add(bookInfoPalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblISBN)
                    .add(lblTitle)
                    .add(lblAth)
                    .add(lblPub)
                    .add(lblSub)
                    .add(lblNoC)
                    .add(lblNoInL)
                    .add(lblWho)
                    .add(lblCallNo))
                .add(18, 18, 18)
                .add(bookInfoPalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblCallNo1)
                    .add(lblISBN1)
                    .add(lblTitle1)
                    .add(lblAth1)
                    .add(lblPub1)
                    .add(lblSub1)
                    .add(lblNoC1)
                    .add(lblNoInL1)
                    .add(lblWho1))
                .addContainerGap(354, Short.MAX_VALUE))
        );
        bookInfoPalLayout.setVerticalGroup(
            bookInfoPalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(bookInfoPalLayout.createSequentialGroup()
                .add(bookInfoPalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(bookInfoPalLayout.createSequentialGroup()
                        .add(lblCallNo1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblISBN1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblTitle1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblAth1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblPub1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblSub1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblNoC1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblNoInL1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblWho1))
                    .add(bookInfoPalLayout.createSequentialGroup()
                        .add(lblCallNo)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblISBN)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblTitle)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblAth)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblPub)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblSub)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblNoC)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblNoInL)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblWho)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnClose.setText("Close");

        scrPanBorBook.setBorder(javax.swing.BorderFactory.createTitledBorder("Book's Borrow Details:"));

        tblBor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scrPanBorBook.setViewportView(tblBor);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(scrPanBorBook, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(btnClose))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(scrPanBorBook, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .add(1, 1, 1)
                .add(btnClose)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(lblImage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 160, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(bookInfoPal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(53, 53, 53)
                        .add(lblImage))
                    .add(layout.createSequentialGroup()
                        .add(11, 11, 11)
                        .add(bookInfoPal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 247, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bookInfoPal;
    private javax.swing.JButton btnClose;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAth;
    private javax.swing.JLabel lblAth1;
    private javax.swing.JLabel lblCallNo;
    private javax.swing.JLabel lblCallNo1;
    private javax.swing.JLabel lblISBN;
    private javax.swing.JLabel lblISBN1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblNoC;
    private javax.swing.JLabel lblNoC1;
    private javax.swing.JLabel lblNoInL;
    private javax.swing.JLabel lblNoInL1;
    private javax.swing.JLabel lblPub;
    private javax.swing.JLabel lblPub1;
    private javax.swing.JLabel lblSub;
    private javax.swing.JLabel lblSub1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblWho;
    private javax.swing.JLabel lblWho1;
    private javax.swing.JScrollPane scrPanBorBook;
    private javax.swing.JTable tblBor;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the btnClose
     */
    public javax.swing.JButton getBtnClose() {
        return btnClose;
    }

    /**
     * @param btnClose the btnClose to set
     */
    public void setBtnClose(javax.swing.JButton btnClose) {
        this.btnClose = btnClose;
    }

    /**
     * @return the lblAth1
     */
    public javax.swing.JLabel getLblAth1() {
        return lblAth1;
    }

    /**
     * @param lblAth1 the lblAth1 to set
     */
    public void setLblAth1(javax.swing.JLabel lblAth1) {
        this.lblAth1 = lblAth1;
    }

    /**
     * @return the lblISBN1
     */
    public javax.swing.JLabel getLblISBN1() {
        return lblISBN1;
    }

    /**
     * @param lblISBN1 the lblISBN1 to set
     */
    public void setLblISBN1(javax.swing.JLabel lblISBN1) {
        this.lblISBN1 = lblISBN1;
    }

    /**
     * @return the lblNoC1
     */
    public javax.swing.JLabel getLblNoC1() {
        return lblNoC1;
    }

    /**
     * @param lblNoC1 the lblNoC1 to set
     */
    public void setLblNoC1(javax.swing.JLabel lblNoC1) {
        this.lblNoC1 = lblNoC1;
    }

    /**
     * @return the lblNoInL1
     */
    public javax.swing.JLabel getLblNoInL1() {
        return lblNoInL1;
    }

    /**
     * @param lblNoInL1 the lblNoInL1 to set
     */
    public void setLblNoInL1(javax.swing.JLabel lblNoInL1) {
        this.lblNoInL1 = lblNoInL1;
    }

    /**
     * @return the lblPub1
     */
    public javax.swing.JLabel getLblPub1() {
        return lblPub1;
    }

    /**
     * @param lblPub1 the lblPub1 to set
     */
    public void setLblPub1(javax.swing.JLabel lblPub1) {
        this.lblPub1 = lblPub1;
    }

    /**
     * @return the lblSub1
     */
    public javax.swing.JLabel getLblSub1() {
        return lblSub1;
    }

    /**
     * @param lblSub1 the lblSub1 to set
     */
    public void setLblSub1(javax.swing.JLabel lblSub1) {
        this.lblSub1 = lblSub1;
    }

    /**
     * @return the lblTitle1
     */
    public javax.swing.JLabel getLblTitle1() {
        return lblTitle1;
    }

    /**
     * @param lblTitle1 the lblTitle1 to set
     */
    public void setLblTitle1(javax.swing.JLabel lblTitle1) {
        this.lblTitle1 = lblTitle1;
    }

    /**
     * @return the lblWho1
     */
    public javax.swing.JLabel getLblWho1() {
        return lblWho1;
    }

    /**
     * @param lblWho1 the lblWho1 to set
     */
    public void setLblWho1(javax.swing.JLabel lblWho1) {
        this.lblWho1 = lblWho1;
    }

    /**
     * @return the lblCallNo1
     */
    public javax.swing.JLabel getLblCallNo1() {
        return lblCallNo1;
    }

    /**
     * @param lblCallNo1 the lblCallNo1 to set
     */
    public void setLblCallNo1(javax.swing.JLabel lblCallNo1) {
        this.lblCallNo1 = lblCallNo1;
    }

    /**
     * @return the tblBor
     */
    public javax.swing.JTable getTblBor() {
        return tblBor;
    }

    /**
     * @param tblBor the tblBor to set
     */
    public void setTblBor(javax.swing.JTable tblBor) {
        this.tblBor = tblBor;
    }

}
