/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ViewEmpDialog.java
 *
 * Created on Jan 2, 2011, 1:51:19 PM
 */
package view;

import entity.Employee;
import java.sql.Date;
import model.LibImages;

/**
 *
 * @author CuongNQ
 */
public class ViewEmpDialog extends javax.swing.JDialog {

    /** Creates new form ViewEmpDialog */
    public ViewEmpDialog(java.awt.Frame parent, boolean modal, Employee emp) {
        super(parent, modal);
        initComponents();
        //Set to center of screen
        setLocationRelativeTo(null);
        //Set field
        setLabel(emp);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblViewImage = new javax.swing.JLabel();
        palInfo = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblPermission = new javax.swing.JLabel();
        lblChkIn = new javax.swing.JLabel();
        lblChkOut = new javax.swing.JLabel();
        lblFee = new javax.swing.JLabel();
        lblID1 = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        lblDOB1 = new javax.swing.JLabel();
        lblGender1 = new javax.swing.JLabel();
        lblEmail1 = new javax.swing.JLabel();
        lblAddress1 = new javax.swing.JLabel();
        lblPhone1 = new javax.swing.JLabel();
        lblPermission1 = new javax.swing.JLabel();
        lblChkIn1 = new javax.swing.JLabel();
        lblChkOut1 = new javax.swing.JLabel();
        lblFee1 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lblViewImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(LibImages.Label_InfoEmp)));

        palInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Employee or Librarian Information"));

        lblID.setText("ID:");

        lblName.setText("Name:");

        lblDOB.setText("Date of birth:");

        lblGender.setText("Gender:");

        lblEmail.setText("Email:");

        lblAddress.setText("Address:");

        lblPhone.setText("Phone:");

        lblPermission.setText("Permission:");

        lblChkIn.setText("Check-in:");

        lblChkOut.setText("Check-out:");

        lblFee.setText("Total fee:");

        lblID1.setText("Empty");

        lblName1.setText("Empty");

        lblDOB1.setText("Empty");

        lblGender1.setText("Empty");

        lblEmail1.setText("Empty");

        lblAddress1.setText("Empty");

        lblPhone1.setText("Empty");

        lblPermission1.setText("Empty");

        lblChkIn1.setText("Empty");

        lblChkOut1.setText("Empty");

        lblFee1.setText("Empty");

        org.jdesktop.layout.GroupLayout palInfoLayout = new org.jdesktop.layout.GroupLayout(palInfo);
        palInfo.setLayout(palInfoLayout);
        palInfoLayout.setHorizontalGroup(
            palInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(palInfoLayout.createSequentialGroup()
                .addContainerGap()
                .add(palInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(palInfoLayout.createSequentialGroup()
                        .add(palInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblID)
                            .add(lblName)
                            .add(lblDOB)
                            .add(lblGender)
                            .add(lblEmail)
                            .add(lblAddress)
                            .add(lblPhone)
                            .add(lblPermission)
                            .add(lblChkIn)
                            .add(lblChkOut))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(palInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblID1)
                            .add(lblName1)
                            .add(lblDOB1)
                            .add(lblGender1)
                            .add(lblEmail1)
                            .add(lblAddress1)
                            .add(lblPhone1)
                            .add(lblPermission1)
                            .add(lblChkIn1)
                            .add(lblChkOut1)
                            .add(lblFee1)))
                    .add(lblFee))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        palInfoLayout.setVerticalGroup(
            palInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(palInfoLayout.createSequentialGroup()
                .add(13, 13, 13)
                .add(palInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(palInfoLayout.createSequentialGroup()
                        .add(lblID1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblName1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblDOB1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblGender1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblEmail1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblAddress1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblPhone1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblPermission1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblChkIn1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblChkOut1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblFee1))
                    .add(palInfoLayout.createSequentialGroup()
                        .add(lblID)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblName)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblDOB)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblGender)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblEmail)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblAddress)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblPhone)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblPermission)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblChkIn)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblChkOut)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblFee)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(lblViewImage)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(palInfo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, btnClose)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(78, 78, 78)
                        .add(lblViewImage))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(palInfo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(btnClose))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        //Close this dialog
        dispose();
}//GEN-LAST:event_btnCloseActionPerformed

    /*
     * Set all information
     */
    private void setLabel(Employee emp) {
        lblID1.setText(new Integer(emp.getEmpID()).toString());
        lblName1.setText(emp.getName());
        lblDOB1.setText(new Date(emp.getDOB()).toString());
        if (emp.getGender() == 1) {
            lblGender1.setText("Male");
        } else {
            lblGender1.setText("Female");
        }
        lblEmail1.setText(emp.getEmail());
        lblAddress1.setText(emp.getAddress());
        lblPhone1.setText(emp.getPhone());
        if (emp.getPermission() == 1) {
            lblPermission1.setText("Librarian");
        } else {
            lblPermission1.setText("Employee");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAddress1;
    private javax.swing.JLabel lblChkIn;
    private javax.swing.JLabel lblChkIn1;
    private javax.swing.JLabel lblChkOut;
    private javax.swing.JLabel lblChkOut1;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDOB1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblFee;
    private javax.swing.JLabel lblFee1;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGender1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblID1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblPermission;
    private javax.swing.JLabel lblPermission1;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhone1;
    private javax.swing.JLabel lblViewImage;
    private javax.swing.JPanel palInfo;
    // End of variables declaration//GEN-END:variables
}
