/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ViewBorrowDialog.java
 *
 * Created on Jan 7, 2011, 12:47:15 PM
 */

package view;

import model.LibImages;

/**
 *
 * @author CuongNQ
 */
public class ViewBorrowDialog extends javax.swing.JDialog {

    /** Creates new form ViewBorrowDialog */
    public ViewBorrowDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        palInfo = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblPermission = new javax.swing.JLabel();
        lblID1 = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        lblDOB1 = new javax.swing.JLabel();
        lblGender1 = new javax.swing.JLabel();
        lblEmail1 = new javax.swing.JLabel();
        lblAddress1 = new javax.swing.JLabel();
        lblPhone1 = new javax.swing.JLabel();
        lblPermission1 = new javax.swing.JLabel();
        lblDepart1 = new javax.swing.JLabel();
        lblDepart = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        palInfo1 = new javax.swing.JPanel();
        lblBorID = new javax.swing.JLabel();
        lblIssueStatus = new javax.swing.JLabel();
        lblIssueDate = new javax.swing.JLabel();
        lblDueDate = new javax.swing.JLabel();
        lblReDate = new javax.swing.JLabel();
        lblCallNo = new javax.swing.JLabel();
        lblISBN = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblBorID1 = new javax.swing.JLabel();
        lblIssueStatus1 = new javax.swing.JLabel();
        lblIssueDate1 = new javax.swing.JLabel();
        lblDueDate1 = new javax.swing.JLabel();
        lblReDate1 = new javax.swing.JLabel();
        lblCallNo1 = new javax.swing.JLabel();
        lblISBN1 = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblTolFee1 = new javax.swing.JLabel();
        lblTolFee = new javax.swing.JLabel();
        lblPublisher = new javax.swing.JLabel();
        lblAuth = new javax.swing.JLabel();
        lblAuth1 = new javax.swing.JLabel();
        lblPublisher1 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(632, 540));

        palInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Employee Infomation"));

        lblID.setText("ID:");

        lblName.setText("Name:");

        lblDOB.setText("Date of birth:");

        lblGender.setText("Gender:");

        lblEmail.setText("Email:");

        lblAddress.setText("Address:");

        lblPhone.setText("Phone:");

        lblPermission.setText("Permission:");

        lblID1.setText("Empty");

        lblName1.setText("Empty");

        lblDOB1.setText("Empty");

        lblGender1.setText("Empty");

        lblEmail1.setText("Empty");

        lblAddress1.setText("Empty");

        lblPhone1.setText("Empty");

        lblPermission1.setText("Empty");

        lblDepart1.setText("Empty");

        lblDepart.setText("Department:");

        org.jdesktop.layout.GroupLayout palInfoLayout = new org.jdesktop.layout.GroupLayout(palInfo);
        palInfo.setLayout(palInfoLayout);
        palInfoLayout.setHorizontalGroup(
            palInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(palInfoLayout.createSequentialGroup()
                .addContainerGap()
                .add(palInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblID)
                    .add(lblName)
                    .add(lblDOB)
                    .add(lblGender)
                    .add(lblEmail)
                    .add(lblAddress)
                    .add(lblPhone)
                    .add(lblPermission)
                    .add(lblDepart))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(palInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblEmail1)
                    .add(lblGender1)
                    .add(lblDOB1)
                    .add(lblName1)
                    .add(lblID1)
                    .add(lblAddress1)
                    .add(lblPhone1)
                    .add(lblPermission1)
                    .add(lblDepart1))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        palInfoLayout.setVerticalGroup(
            palInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(palInfoLayout.createSequentialGroup()
                .add(13, 13, 13)
                .add(palInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(palInfoLayout.createSequentialGroup()
                        .add(lblAddress1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblPhone1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblPermission1))
                    .add(palInfoLayout.createSequentialGroup()
                        .add(palInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lblID)
                            .add(lblID1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(palInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lblName)
                            .add(lblName1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(palInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lblDOB)
                            .add(lblDOB1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(palInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lblGender)
                            .add(lblGender1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(palInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lblEmail)
                            .add(lblEmail1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(palInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lblDepart)
                            .add(lblDepart1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblAddress)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblPhone)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblPermission)))
                .addContainerGap(6, Short.MAX_VALUE))
        );

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(LibImages.LABEL_INFOBOR)));

        palInfo1.setBorder(javax.swing.BorderFactory.createTitledBorder("Borrow Infomation"));

        lblBorID.setText("Borrow ID:");

        lblIssueStatus.setText("IssueStatus:");

        lblIssueDate.setText("IssueDate:");

        lblDueDate.setText("DueDate:");

        lblReDate.setText("Return Date:");

        lblCallNo.setText("CallNumber:");

        lblISBN.setText("ISBN:");

        lblTitle.setText("Title:");

        lblBorID1.setText("Empty");

        lblIssueStatus1.setText("Empty");

        lblIssueDate1.setText("Empty");

        lblDueDate1.setText("Empty");

        lblReDate1.setText("Empty");

        lblCallNo1.setText("Empty");

        lblISBN1.setText("Empty");

        lblTitle1.setText("Empty");

        lblTolFee1.setText("Empty");

        lblTolFee.setText("Total Fee:");

        lblPublisher.setText("Publisher:");

        lblAuth.setText("AuthName:");

        lblAuth1.setText("Empty");

        lblPublisher1.setText("Empty");

        btnClose.setText("Close");

        org.jdesktop.layout.GroupLayout palInfo1Layout = new org.jdesktop.layout.GroupLayout(palInfo1);
        palInfo1.setLayout(palInfo1Layout);
        palInfo1Layout.setHorizontalGroup(
            palInfo1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(palInfo1Layout.createSequentialGroup()
                .addContainerGap()
                .add(palInfo1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblBorID)
                    .add(lblDueDate)
                    .add(lblReDate)
                    .add(lblIssueStatus)
                    .add(lblIssueDate)
                    .add(lblTolFee))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(palInfo1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblBorID1)
                    .add(lblIssueDate1)
                    .add(lblIssueStatus1)
                    .add(lblDueDate1)
                    .add(lblReDate1)
                    .add(lblTolFee1))
                .add(palInfo1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(palInfo1Layout.createSequentialGroup()
                        .add(56, 56, 56)
                        .add(palInfo1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblCallNo)
                            .add(lblAuth)
                            .add(lblTitle)
                            .add(lblPublisher)
                            .add(lblISBN))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(palInfo1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblCallNo1)
                            .add(lblTitle1)
                            .add(lblISBN1)
                            .add(lblPublisher1)
                            .add(lblAuth1))
                        .addContainerGap(242, Short.MAX_VALUE))
                    .add(palInfo1Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnClose))))
        );
        palInfo1Layout.setVerticalGroup(
            palInfo1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(palInfo1Layout.createSequentialGroup()
                .add(40, 40, 40)
                .add(palInfo1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(lblBorID1)
                    .add(lblBorID)
                    .add(lblCallNo)
                    .add(lblCallNo1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(palInfo1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(lblIssueStatus1)
                    .add(lblISBN)
                    .add(lblISBN1)
                    .add(lblIssueStatus))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(palInfo1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(lblTitle)
                    .add(lblIssueDate1)
                    .add(lblTitle1)
                    .add(lblIssueDate))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(palInfo1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(lblAuth)
                    .add(lblDueDate1)
                    .add(lblAuth1)
                    .add(lblDueDate))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(palInfo1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(lblPublisher1)
                    .add(lblPublisher)
                    .add(lblReDate1)
                    .add(lblReDate))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(palInfo1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(lblTolFee1)
                    .add(lblTolFee))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, palInfo1Layout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .add(btnClose))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, palInfo1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(lblImage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(palInfo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, palInfo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 255, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(lblImage)
                        .add(48, 48, 48)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(palInfo1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAddress1;
    private javax.swing.JLabel lblAuth;
    private javax.swing.JLabel lblAuth1;
    private javax.swing.JLabel lblBorID;
    private javax.swing.JLabel lblBorID1;
    private javax.swing.JLabel lblCallNo;
    private javax.swing.JLabel lblCallNo1;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDOB1;
    private javax.swing.JLabel lblDepart;
    private javax.swing.JLabel lblDepart1;
    private javax.swing.JLabel lblDueDate;
    private javax.swing.JLabel lblDueDate1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGender1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblID1;
    private javax.swing.JLabel lblISBN;
    private javax.swing.JLabel lblISBN1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblIssueDate;
    private javax.swing.JLabel lblIssueDate1;
    private javax.swing.JLabel lblIssueStatus;
    private javax.swing.JLabel lblIssueStatus1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblPermission;
    private javax.swing.JLabel lblPermission1;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhone1;
    private javax.swing.JLabel lblPublisher;
    private javax.swing.JLabel lblPublisher1;
    private javax.swing.JLabel lblReDate;
    private javax.swing.JLabel lblReDate1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTolFee;
    private javax.swing.JLabel lblTolFee1;
    private javax.swing.JPanel palInfo;
    private javax.swing.JPanel palInfo1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the lblAddress1
     */
    public javax.swing.JLabel getLblAddress1() {
        return lblAddress1;
    }

    /**
     * @param lblAddress1 the lblAddress1 to set
     */
    public void setLblAddress1(javax.swing.JLabel lblAddress1) {
        this.lblAddress1 = lblAddress1;
    }

    /**
     * @return the lblAuth1
     */
    public javax.swing.JLabel getLblAuth1() {
        return lblAuth1;
    }

    /**
     * @param lblAuth1 the lblAuth1 to set
     */
    public void setLblAuth1(javax.swing.JLabel lblAuth1) {
        this.lblAuth1 = lblAuth1;
    }

    /**
     * @return the lblBorID1
     */
    public javax.swing.JLabel getLblBorID1() {
        return lblBorID1;
    }

    /**
     * @param lblBorID1 the lblBorID1 to set
     */
    public void setLblBorID1(javax.swing.JLabel lblBorID1) {
        this.lblBorID1 = lblBorID1;
    }

    /**
     * @return the lblCallNo1
     */
    public javax.swing.JLabel getLblCallNo1() {
        return lblCallNo1;
    }

    /**
     * @param lblCallNo1 the lblCallNo1 to set
     */
    public void setLblCallNo1(javax.swing.JLabel lblCallNo1) {
        this.lblCallNo1 = lblCallNo1;
    }

    /**
     * @return the lblDOB1
     */
    public javax.swing.JLabel getLblDOB1() {
        return lblDOB1;
    }

    /**
     * @param lblDOB1 the lblDOB1 to set
     */
    public void setLblDOB1(javax.swing.JLabel lblDOB1) {
        this.lblDOB1 = lblDOB1;
    }

    /**
     * @return the lblDepart1
     */
    public javax.swing.JLabel getLblDepart1() {
        return lblDepart1;
    }

    /**
     * @param lblDepart1 the lblDepart1 to set
     */
    public void setLblDepart1(javax.swing.JLabel lblDepart1) {
        this.lblDepart1 = lblDepart1;
    }

    /**
     * @return the lblDueDate1
     */
    public javax.swing.JLabel getLblDueDate1() {
        return lblDueDate1;
    }

    /**
     * @param lblDueDate1 the lblDueDate1 to set
     */
    public void setLblDueDate1(javax.swing.JLabel lblDueDate1) {
        this.lblDueDate1 = lblDueDate1;
    }

    /**
     * @return the lblEmail1
     */
    public javax.swing.JLabel getLblEmail1() {
        return lblEmail1;
    }

    /**
     * @param lblEmail1 the lblEmail1 to set
     */
    public void setLblEmail1(javax.swing.JLabel lblEmail1) {
        this.lblEmail1 = lblEmail1;
    }

    /**
     * @return the lblGender1
     */
    public javax.swing.JLabel getLblGender1() {
        return lblGender1;
    }

    /**
     * @param lblGender1 the lblGender1 to set
     */
    public void setLblGender1(javax.swing.JLabel lblGender1) {
        this.lblGender1 = lblGender1;
    }

    /**
     * @return the lblID1
     */
    public javax.swing.JLabel getLblID1() {
        return lblID1;
    }

    /**
     * @param lblID1 the lblID1 to set
     */
    public void setLblID1(javax.swing.JLabel lblID1) {
        this.lblID1 = lblID1;
    }

    /**
     * @return the lblISBN1
     */
    public javax.swing.JLabel getLblISBN1() {
        return lblISBN1;
    }

    /**
     * @param lblISBN1 the lblISBN1 to set
     */
    public void setLblISBN1(javax.swing.JLabel lblISBN1) {
        this.lblISBN1 = lblISBN1;
    }

    /**
     * @return the lblIssueDate1
     */
    public javax.swing.JLabel getLblIssueDate1() {
        return lblIssueDate1;
    }

    /**
     * @param lblIssueDate1 the lblIssueDate1 to set
     */
    public void setLblIssueDate1(javax.swing.JLabel lblIssueDate1) {
        this.lblIssueDate1 = lblIssueDate1;
    }

    /**
     * @return the lblIssueStatus1
     */
    public javax.swing.JLabel getLblIssueStatus1() {
        return lblIssueStatus1;
    }

    /**
     * @param lblIssueStatus1 the lblIssueStatus1 to set
     */
    public void setLblIssueStatus1(javax.swing.JLabel lblIssueStatus1) {
        this.lblIssueStatus1 = lblIssueStatus1;
    }

    /**
     * @return the lblName1
     */
    public javax.swing.JLabel getLblName1() {
        return lblName1;
    }

    /**
     * @param lblName1 the lblName1 to set
     */
    public void setLblName1(javax.swing.JLabel lblName1) {
        this.lblName1 = lblName1;
    }

    /**
     * @return the lblPermission1
     */
    public javax.swing.JLabel getLblPermission1() {
        return lblPermission1;
    }

    /**
     * @param lblPermission1 the lblPermission1 to set
     */
    public void setLblPermission1(javax.swing.JLabel lblPermission1) {
        this.lblPermission1 = lblPermission1;
    }

    /**
     * @return the lblPhone1
     */
    public javax.swing.JLabel getLblPhone1() {
        return lblPhone1;
    }

    /**
     * @param lblPhone1 the lblPhone1 to set
     */
    public void setLblPhone1(javax.swing.JLabel lblPhone1) {
        this.lblPhone1 = lblPhone1;
    }

    /**
     * @return the lblPublisher1
     */
    public javax.swing.JLabel getLblPublisher1() {
        return lblPublisher1;
    }

    /**
     * @param lblPublisher1 the lblPublisher1 to set
     */
    public void setLblPublisher1(javax.swing.JLabel lblPublisher1) {
        this.lblPublisher1 = lblPublisher1;
    }

    /**
     * @return the lblReDate1
     */
    public javax.swing.JLabel getLblReDate1() {
        return lblReDate1;
    }

    /**
     * @param lblReDate1 the lblReDate1 to set
     */
    public void setLblReDate1(javax.swing.JLabel lblReDate1) {
        this.lblReDate1 = lblReDate1;
    }

    /**
     * @return the lblTitle1
     */
    public javax.swing.JLabel getLblTitle1() {
        return lblTitle1;
    }

    /**
     * @param lblTitle1 the lblTitle1 to set
     */
    public void setLblTitle1(javax.swing.JLabel lblTitle1) {
        this.lblTitle1 = lblTitle1;
    }

    /**
     * @return the lblTolFee1
     */
    public javax.swing.JLabel getLblTolFee1() {
        return lblTolFee1;
    }

    /**
     * @param lblTolFee1 the lblTolFee1 to set
     */
    public void setLblTolFee1(javax.swing.JLabel lblTolFee1) {
        this.lblTolFee1 = lblTolFee1;
    }

    /**
     * @return the palInfo1
     */
    public javax.swing.JPanel getPalInfo1() {
        return palInfo1;
    }

    /**
     * @param palInfo1 the palInfo1 to set
     */
    public void setPalInfo1(javax.swing.JPanel palInfo1) {
        this.palInfo1 = palInfo1;
    }

    /**
     * @return the btnClose
     */
    public javax.swing.JButton getBtnClose() {
        return btnClose;
    }

    /**
     * @param btnClose the btnClose to set
     */
    public void setBtnClose(javax.swing.JButton btnClose) {
        this.btnClose = btnClose;
    }

}
