/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * manageFrm.java
 *
 * Created on Dec 28, 2010, 8:30:10 PM
 */
package GUI;

import java.awt.*;
import java.io.File;
import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author CuongNQ
 */
public class manageFrm extends javax.swing.JFrame {

    //Defined Icon
    Icon iconBook;
    Icon iconEmp;
    Icon iconBor;
    Icon iconSub;
    Icon iconAna;
    //Defined Jlabel
    JLabel lblBook;
    JLabel lblEmp;
    JLabel lblBor;
    JLabel lblSub;
    JLabel lblAna;
    //Defined Panel
    JPanel palBookIcon;
    JPanel palEmpIcon;
    JPanel palBorIcon;
    JPanel palSubIcon;
    JPanel palAnaIcon;

    /** Creates new form manageFrm */
    public manageFrm() {
        //All component
        initComponents();
        //Set this frame to center of monitor
        setLocationRelativeTo(null);
        //Left menu
        listMenuDesign();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splPanel = new javax.swing.JSplitPane();
        scrPanMenu = new javax.swing.JScrollPane();
        lstMenu = new javax.swing.JList();
        palMain = new javax.swing.JPanel();
        palBook = new javax.swing.JPanel();
        tolbarEmp = new javax.swing.JToolBar();
        btnAddEmp = new javax.swing.JButton();
        separator1 = new javax.swing.JToolBar.Separator();
        btnEditEmp = new javax.swing.JButton();
        btnViewEmp = new javax.swing.JButton();
        btnDeleteEmp = new javax.swing.JButton();
        separator2 = new javax.swing.JToolBar.Separator();
        btnSearchEmp = new javax.swing.JButton();
        scrPanEmp = new javax.swing.JScrollPane();
        tblEmp = new javax.swing.JTable();
        txtIDEmpSearch = new javax.swing.JTextField();
        lblIDEmpSearch = new javax.swing.JLabel();
        txtNameEmpSearch = new javax.swing.JTextField();
        lblNameEmpSearch = new javax.swing.JLabel();
        palSubject = new javax.swing.JPanel();
        palBorrow = new javax.swing.JPanel();
        palAnalytic = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        mnSystem = new javax.swing.JMenu();
        menuSetting = new javax.swing.JMenuItem();
        separator = new javax.swing.JPopupMenu.Separator();
        mnQuit = new javax.swing.JMenuItem();
        mnHelp = new javax.swing.JMenu();
        mnSubHelp = new javax.swing.JMenuItem();
        mnAbout = new javax.swing.JMenuItem();
        mnEmp = new javax.swing.JMenu();
        mnBook = new javax.swing.JMenu();
        mbSub = new javax.swing.JMenu();
        mnBor = new javax.swing.JMenu();
        mnAna = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(580, 280));
        setName("mainFrm"); // NOI18N

        splPanel.setDividerLocation(120);

        lstMenu.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstMenu.setFocusable(false);
        lstMenu.setOpaque(false);
        lstMenu.setSize(new java.awt.Dimension(100, 200));
        scrPanMenu.setViewportView(lstMenu);

        splPanel.setLeftComponent(scrPanMenu);

        palMain.setLayout(new java.awt.CardLayout());

        tolbarEmp.setBorder(null);
        tolbarEmp.setFloatable(false);
        tolbarEmp.setBorderPainted(false);
        tolbarEmp.setOpaque(false);

        btnAddEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/addIcon.png"))); // NOI18N
        btnAddEmp.setMnemonic('a');
        btnAddEmp.setText("Add");
        btnAddEmp.setBorderPainted(false);
        btnAddEmp.setFocusable(false);
        btnAddEmp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddEmp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmpActionPerformed(evt);
            }
        });
        tolbarEmp.add(btnAddEmp);
        tolbarEmp.add(separator1);

        btnEditEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/editIcon.png"))); // NOI18N
        btnEditEmp.setMnemonic('e');
        btnEditEmp.setText("Edit");
        btnEditEmp.setBorderPainted(false);
        btnEditEmp.setEnabled(false);
        btnEditEmp.setFocusable(false);
        btnEditEmp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditEmp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tolbarEmp.add(btnEditEmp);

        btnViewEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/viewIcon.png"))); // NOI18N
        btnViewEmp.setMnemonic('v');
        btnViewEmp.setText("View");
        btnViewEmp.setBorderPainted(false);
        btnViewEmp.setEnabled(false);
        btnViewEmp.setFocusable(false);
        btnViewEmp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnViewEmp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tolbarEmp.add(btnViewEmp);

        btnDeleteEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/deleteIcon.png"))); // NOI18N
        btnDeleteEmp.setMnemonic('d');
        btnDeleteEmp.setText("Delete");
        btnDeleteEmp.setBorderPainted(false);
        btnDeleteEmp.setEnabled(false);
        btnDeleteEmp.setFocusable(false);
        btnDeleteEmp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeleteEmp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tolbarEmp.add(btnDeleteEmp);
        tolbarEmp.add(separator2);

        btnSearchEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/searchIcon.png"))); // NOI18N
        btnSearchEmp.setText("Search");
        btnSearchEmp.setBorderPainted(false);
        btnSearchEmp.setFocusable(false);
        btnSearchEmp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSearchEmp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tolbarEmp.add(btnSearchEmp);

        tblEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scrPanEmp.setViewportView(tblEmp);

        txtIDEmpSearch.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N

        lblIDEmpSearch.setText("ISBN:");

        txtNameEmpSearch.setFont(new java.awt.Font("Lucida Grande", 0, 12));

        lblNameEmpSearch.setText("CallNo:");

        org.jdesktop.layout.GroupLayout palBookLayout = new org.jdesktop.layout.GroupLayout(palBook);
        palBook.setLayout(palBookLayout);
        palBookLayout.setHorizontalGroup(
            palBookLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 620, Short.MAX_VALUE)
            .add(scrPanEmp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
            .add(palBookLayout.createSequentialGroup()
                .add(tolbarEmp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(palBookLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblIDEmpSearch)
                    .add(lblNameEmpSearch))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(palBookLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(txtNameEmpSearch)
                    .add(txtIDEmpSearch, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addContainerGap())
        );
        palBookLayout.setVerticalGroup(
            palBookLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 406, Short.MAX_VALUE)
            .add(palBookLayout.createSequentialGroup()
                .add(palBookLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(tolbarEmp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(palBookLayout.createSequentialGroup()
                        .add(palBookLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtIDEmpSearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblIDEmpSearch))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(palBookLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtNameEmpSearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblNameEmpSearch))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(scrPanEmp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE))
        );

        palMain.add(new palEmployee(), "palEmployee");

        palMain.add(palBook, "palBook");

        org.jdesktop.layout.GroupLayout palSubjectLayout = new org.jdesktop.layout.GroupLayout(palSubject);
        palSubject.setLayout(palSubjectLayout);
        palSubjectLayout.setHorizontalGroup(
            palSubjectLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 620, Short.MAX_VALUE)
        );
        palSubjectLayout.setVerticalGroup(
            palSubjectLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 406, Short.MAX_VALUE)
        );

        palMain.add(palSubject, "palSubject");

        org.jdesktop.layout.GroupLayout palBorrowLayout = new org.jdesktop.layout.GroupLayout(palBorrow);
        palBorrow.setLayout(palBorrowLayout);
        palBorrowLayout.setHorizontalGroup(
            palBorrowLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 620, Short.MAX_VALUE)
        );
        palBorrowLayout.setVerticalGroup(
            palBorrowLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 406, Short.MAX_VALUE)
        );

        palMain.add(palBorrow, "palBorrow");

        org.jdesktop.layout.GroupLayout palAnalyticLayout = new org.jdesktop.layout.GroupLayout(palAnalytic);
        palAnalytic.setLayout(palAnalyticLayout);
        palAnalyticLayout.setHorizontalGroup(
            palAnalyticLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 620, Short.MAX_VALUE)
        );
        palAnalyticLayout.setVerticalGroup(
            palAnalyticLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 406, Short.MAX_VALUE)
        );

        palMain.add(palAnalytic, "palAnalytic");

        splPanel.setRightComponent(palMain);

        mnSystem.setText("System");

        menuSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/settingMenu.png"))); // NOI18N
        menuSetting.setText("Setting");
        mnSystem.add(menuSetting);
        mnSystem.add(separator);

        mnQuit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        mnQuit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/quitIcon.png"))); // NOI18N
        mnQuit.setText("Quit");
        mnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnQuitActionPerformed(evt);
            }
        });
        mnSystem.add(mnQuit);

        menuBar.add(mnSystem);

        mnHelp.setText("Help");

        mnSubHelp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        mnSubHelp.setText("Help");
        mnHelp.add(mnSubHelp);

        mnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/aboutMenu.png"))); // NOI18N
        mnAbout.setText("About us");
        mnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAboutActionPerformed(evt);
            }
        });
        mnHelp.add(mnAbout);

        menuBar.add(mnHelp);

        mnEmp.setText("Employees");
        menuBar.add(mnEmp);

        mnBook.setText("Books");
        menuBar.add(mnBook);

        mbSub.setText("Subjects");
        menuBar.add(mbSub);

        mnBor.setText("Borrows");
        menuBar.add(mnBor);

        mnAna.setText("Analytics");
        menuBar.add(mnAna);

        setJMenuBar(menuBar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(splPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(splPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
     * This method contant the design of left menu, this all of main menu
     * of program
     */
    private void listMenuDesign() {        
        //set split panel not moveable
        splPanel.setDividerSize(0);
        //construct the menuList as a JList
        lstMenu.setCellRenderer(new ImageListCellRenderer());
        //get our icon
        iconEmp = new ImageIcon(getClass().getResource(
                "Images" + File.separator + "employeeIcon.png"));
        iconBook = new ImageIcon(getClass().getResource(
                "Images" + File.separator + "bookIcon.png"));
        iconSub = new ImageIcon(getClass().getResource(
                "Images" + File.separator + "subIcon.png"));
        iconBor = new ImageIcon(getClass().getResource(
                "Images" + File.separator + "borIcon.png"));
        iconAna = new ImageIcon(getClass().getResource(
                "Images" + File.separator + "anaIcon.png"));
        //add the images to jlabels with text
        lblEmp = new JLabel("Employees", iconEmp, JLabel.LEFT);
        lblBook = new JLabel("Books", iconBook, JLabel.LEFT);
        lblSub = new JLabel("Subjects", iconSub, JLabel.LEFT);
        lblBor = new JLabel("Borrows", iconBor, JLabel.LEFT);
        lblAna = new JLabel("Analytics", iconAna, JLabel.LEFT);
        //create the corresponding panels
        palEmpIcon = new JPanel(new FlowLayout(FlowLayout.LEFT));
        palBookIcon = new JPanel(new FlowLayout(FlowLayout.LEFT));
        palSubIcon = new JPanel(new FlowLayout(FlowLayout.LEFT));
        palBorIcon = new JPanel(new FlowLayout(FlowLayout.LEFT));
        palAnaIcon = new JPanel(new FlowLayout(FlowLayout.LEFT));
        //add the labels onto the panels
        palEmpIcon.add(lblEmp);
        palBookIcon.add(lblBook);
        palSubIcon.add(lblSub);
        palBorIcon.add(lblBor);
        palAnaIcon.add(lblAna);
        //create a panel array
        Object[] panels = {palEmpIcon, palBookIcon, palSubIcon, palBorIcon, palAnaIcon};
        //tell the jlist to use the panel array for its data
        lstMenu.setListData(panels);

        //Set selection listener event
        lstMenu.addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent listSelectionEvent) {
                lstMenuActionPerformed(listSelectionEvent);
            }
        });
    }

    /*
     *
     */
    private void lstMenuActionPerformed(ListSelectionEvent evt) {
        //Get current cardlayout
        CardLayout cardlayout=(CardLayout) palMain.getLayout();
        //get menu index and show this panel
        if (!evt.getValueIsAdjusting()) {            
            switch (lstMenu.getAnchorSelectionIndex()) {
                case 0:
                    cardlayout.show(palMain, "palEmployee");
                    break;
                case 1:
                    cardlayout.show(palMain, "palBook");
                    break;
                case 2:
                    cardlayout.show(palMain, "palSubject");
                    break;
                case 3:
                    cardlayout.show(palMain, "palBorrow");
                    break;
                case 4:
                    cardlayout.show(palMain, "palAnalytic");
                    break;
            }
        }
    }

    private void mnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnQuitActionPerformed
        //Dispose this frame
        dispose();
        System.exit(0);
}//GEN-LAST:event_mnQuitActionPerformed

    private void mnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAboutActionPerformed
        //call aboutUs method
        aboutUs();
}//GEN-LAST:event_mnAboutActionPerformed

    private void btnAddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmpActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_btnAddEmpActionPerformed

    /*
     * About method
     */
    private void aboutUs() {
        setVisible(false);//hidden current frame
        new aboutWindow().addWindowListener(new java.awt.event.WindowAdapter() {

            public void windowClosed(java.awt.event.WindowEvent evt) {
                setVisible(true);//show current frame
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new manageFrm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEmp;
    private javax.swing.JButton btnDeleteEmp;
    private javax.swing.JButton btnEditEmp;
    private javax.swing.JButton btnSearchEmp;
    private javax.swing.JButton btnViewEmp;
    private javax.swing.JLabel lblIDEmpSearch;
    private javax.swing.JLabel lblNameEmpSearch;
    private javax.swing.JList lstMenu;
    private javax.swing.JMenu mbSub;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuSetting;
    private javax.swing.JMenuItem mnAbout;
    private javax.swing.JMenu mnAna;
    private javax.swing.JMenu mnBook;
    private javax.swing.JMenu mnBor;
    private javax.swing.JMenu mnEmp;
    private javax.swing.JMenu mnHelp;
    private javax.swing.JMenuItem mnQuit;
    private javax.swing.JMenuItem mnSubHelp;
    private javax.swing.JMenu mnSystem;
    private javax.swing.JPanel palAnalytic;
    private javax.swing.JPanel palBook;
    private javax.swing.JPanel palBorrow;
    private javax.swing.JPanel palMain;
    private javax.swing.JPanel palSubject;
    private javax.swing.JScrollPane scrPanEmp;
    private javax.swing.JScrollPane scrPanMenu;
    private javax.swing.JPopupMenu.Separator separator;
    private javax.swing.JToolBar.Separator separator1;
    private javax.swing.JToolBar.Separator separator2;
    private javax.swing.JSplitPane splPanel;
    private javax.swing.JTable tblEmp;
    private javax.swing.JToolBar tolbarEmp;
    private javax.swing.JTextField txtIDEmpSearch;
    private javax.swing.JTextField txtNameEmpSearch;
    // End of variables declaration//GEN-END:variables
}
