/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * palEmployee.java
 *
 * Created on Dec 30, 2010, 2:37:09 PM
 */

package GUI;

/**
 *
 * @author CuongNQ
 */
public class palEmployee extends javax.swing.JPanel {

    /** Creates new form palEmployee */
    public palEmployee() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tolbarEmp = new javax.swing.JToolBar();
        btnAddEmp = new javax.swing.JButton();
        separator1 = new javax.swing.JToolBar.Separator();
        btnEditEmp = new javax.swing.JButton();
        btnViewEmp = new javax.swing.JButton();
        btnDeleteEmp = new javax.swing.JButton();
        separator2 = new javax.swing.JToolBar.Separator();
        btnSearchEmp = new javax.swing.JButton();
        scrPanEmp = new javax.swing.JScrollPane();
        tblEmp = new javax.swing.JTable();
        txtIDEmpSearch = new javax.swing.JTextField();
        lblIDEmpSearch = new javax.swing.JLabel();
        txtNameEmpSearch = new javax.swing.JTextField();
        lblNameEmpSearch = new javax.swing.JLabel();

        tolbarEmp.setBorder(null);
        tolbarEmp.setFloatable(false);
        tolbarEmp.setBorderPainted(false);
        tolbarEmp.setOpaque(false);

        btnAddEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/addIcon.png"))); // NOI18N
        btnAddEmp.setMnemonic('a');
        btnAddEmp.setText("Add");
        btnAddEmp.setBorderPainted(false);
        btnAddEmp.setFocusable(false);
        btnAddEmp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddEmp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmpActionPerformed(evt);
            }
        });
        tolbarEmp.add(btnAddEmp);
        tolbarEmp.add(separator1);

        btnEditEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/editIcon.png"))); // NOI18N
        btnEditEmp.setMnemonic('e');
        btnEditEmp.setText("Edit");
        btnEditEmp.setBorderPainted(false);
        btnEditEmp.setEnabled(false);
        btnEditEmp.setFocusable(false);
        btnEditEmp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditEmp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tolbarEmp.add(btnEditEmp);

        btnViewEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/viewIcon.png"))); // NOI18N
        btnViewEmp.setMnemonic('v');
        btnViewEmp.setText("View");
        btnViewEmp.setBorderPainted(false);
        btnViewEmp.setEnabled(false);
        btnViewEmp.setFocusable(false);
        btnViewEmp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnViewEmp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tolbarEmp.add(btnViewEmp);

        btnDeleteEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/deleteIcon.png"))); // NOI18N
        btnDeleteEmp.setMnemonic('d');
        btnDeleteEmp.setText("Delete");
        btnDeleteEmp.setBorderPainted(false);
        btnDeleteEmp.setEnabled(false);
        btnDeleteEmp.setFocusable(false);
        btnDeleteEmp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeleteEmp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tolbarEmp.add(btnDeleteEmp);
        tolbarEmp.add(separator2);

        btnSearchEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/searchIcon.png"))); // NOI18N
        btnSearchEmp.setText("Search");
        btnSearchEmp.setBorderPainted(false);
        btnSearchEmp.setFocusable(false);
        btnSearchEmp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSearchEmp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tolbarEmp.add(btnSearchEmp);

        tblEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scrPanEmp.setViewportView(tblEmp);

        txtIDEmpSearch.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N

        lblIDEmpSearch.setText("ID:");

        txtNameEmpSearch.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N

        lblNameEmpSearch.setText("Name:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 427, Short.MAX_VALUE)
            .add(scrPanEmp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(tolbarEmp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblIDEmpSearch)
                    .add(lblNameEmpSearch))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(txtNameEmpSearch, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, txtIDEmpSearch, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 289, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(tolbarEmp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtIDEmpSearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblIDEmpSearch))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtNameEmpSearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblNameEmpSearch))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(scrPanEmp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmpActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_btnAddEmpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEmp;
    private javax.swing.JButton btnDeleteEmp;
    private javax.swing.JButton btnEditEmp;
    private javax.swing.JButton btnSearchEmp;
    private javax.swing.JButton btnViewEmp;
    private javax.swing.JLabel lblIDEmpSearch;
    private javax.swing.JLabel lblNameEmpSearch;
    private javax.swing.JScrollPane scrPanEmp;
    private javax.swing.JToolBar.Separator separator1;
    private javax.swing.JToolBar.Separator separator2;
    private javax.swing.JTable tblEmp;
    private javax.swing.JToolBar tolbarEmp;
    private javax.swing.JTextField txtIDEmpSearch;
    private javax.swing.JTextField txtNameEmpSearch;
    // End of variables declaration//GEN-END:variables

}
