/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PalAnalytic.java
 *
 * Created on Jan 3, 2011, 6:05:03 PM
 */

package view;

import model.LibImages;

/**
 *
 * @author CuongNQ
 */
public class PalAnalytic extends javax.swing.JPanel {

    /** Creates new form PalAnalytic */
    public PalAnalytic() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tolbarAna = new javax.swing.JToolBar();
        btnTBookAna = new javax.swing.JButton();
        btnTBorAna = new javax.swing.JButton();
        btnAlertAna = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        lblISBNBook = new javax.swing.JLabel();
        txtIssueDate = new org.jdesktop.swingx.JXDatePicker();
        txtDueDate = new org.jdesktop.swingx.JXDatePicker();
        jPanel1 = new javax.swing.JPanel();
        scrPanAna = new javax.swing.JScrollPane();
        tblAna = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnFirst = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtPage = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();

        setToolTipText("show details");

        tolbarAna.setBorder(null);
        tolbarAna.setFloatable(false);
        tolbarAna.setBorderPainted(false);
        tolbarAna.setOpaque(false);

        btnTBookAna.setIcon(new javax.swing.ImageIcon(getClass().getResource(LibImages.TASKBAR_TOPBOOK)));
        btnTBookAna.setMnemonic('a');
        btnTBookAna.setText("Top Book");
        btnTBookAna.setBorderPainted(false);
        btnTBookAna.setFocusable(false);
        btnTBookAna.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTBookAna.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tolbarAna.add(btnTBookAna);

        btnTBorAna.setIcon(new javax.swing.ImageIcon(getClass().getResource(LibImages.TASKBAR_TOPBORROWER)));
        btnTBorAna.setMnemonic('e');
        btnTBorAna.setText("Top Borrower");
        btnTBorAna.setBorderPainted(false);
        btnTBorAna.setFocusable(false);
        btnTBorAna.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTBorAna.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tolbarAna.add(btnTBorAna);

        btnAlertAna.setIcon(new javax.swing.ImageIcon(getClass().getResource(LibImages.TASKBAR_SENDALERT)));
        btnAlertAna.setMnemonic('s');
        btnAlertAna.setText("Overdue Alert");
        btnAlertAna.setBorderPainted(false);
        btnAlertAna.setEnabled(false);
        btnAlertAna.setFocusable(false);
        btnAlertAna.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAlertAna.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tolbarAna.add(btnAlertAna);

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource(LibImages.TASKBAR_SEARCH)));
        btnSearch.setText("Search");
        btnSearch.setBorderPainted(false);
        btnSearch.setFocusable(false);
        btnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSearch.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tolbarAna.add(btnSearch);

        lblISBNBook.setText("Issue | Due Date:");
        tolbarAna.add(lblISBNBook);
        tolbarAna.add(txtIssueDate);
        tolbarAna.add(txtDueDate);

        jPanel1.setLayout(new java.awt.BorderLayout());

        tblAna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scrPanAna.setViewportView(tblAna);

        jPanel1.add(scrPanAna, java.awt.BorderLayout.CENTER);

        btnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource(LibImages.TASKBAR_FIRST)));
        btnFirst.setBorderPainted(false);
        jPanel2.add(btnFirst);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource(LibImages.TASKBAR_BACK)));
        btnBack.setBorderPainted(false);
        jPanel2.add(btnBack);

        txtPage.setText("Pages");
        jPanel2.add(txtPage);

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource(LibImages.TASKBAR_NEXT)));
        btnNext.setBorderPainted(false);
        jPanel2.add(btnNext);

        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource(LibImages.TASKBAR_LAST)));
        btnLast.setBorderPainted(false);
        jPanel2.add(btnLast);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tolbarAna, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(tolbarAna, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(323, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(50, 50, 50)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlertAna;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnTBookAna;
    private javax.swing.JButton btnTBorAna;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblISBNBook;
    private javax.swing.JScrollPane scrPanAna;
    private javax.swing.JTable tblAna;
    private javax.swing.JToolBar tolbarAna;
    private org.jdesktop.swingx.JXDatePicker txtDueDate;
    private org.jdesktop.swingx.JXDatePicker txtIssueDate;
    private javax.swing.JLabel txtPage;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the btnAlertAna
     */
    public javax.swing.JButton getBtnAlertAna() {
        return btnAlertAna;
    }

    /**
     * @param btnAlertAna the btnAlertAna to set
     */
    public void setBtnAlertAna(javax.swing.JButton btnAlertAna) {
        this.btnAlertAna = btnAlertAna;
    }

    /**
     * @return the btnTBookAna
     */
    public javax.swing.JButton getBtnTBookAna() {
        return btnTBookAna;
    }

    /**
     * @param btnTBookAna the btnTBookAna to set
     */
    public void setBtnTBookAna(javax.swing.JButton btnTBookAna) {
        this.btnTBookAna = btnTBookAna;
    }

    /**
     * @return the btnTBorAna
     */
    public javax.swing.JButton getBtnTBorAna() {
        return btnTBorAna;
    }

    /**
     * @param btnTBorAna the btnTBorAna to set
     */
    public void setBtnTBorAna(javax.swing.JButton btnTBorAna) {
        this.btnTBorAna = btnTBorAna;
    }

    /**
     * @return the tblAna
     */
    public javax.swing.JTable getTblAna() {
        return tblAna;
    }

    /**
     * @param tblAna the tblAna to set
     */
    public void setTblAna(javax.swing.JTable tblAna) {
        this.tblAna = tblAna;
    }

    /**
     * @return the btnBack
     */
    public javax.swing.JButton getBtnBack() {
        return btnBack;
    }

    /**
     * @param btnBack the btnBack to set
     */
    public void setBtnBack(javax.swing.JButton btnBack) {
        this.btnBack = btnBack;
    }

    /**
     * @return the btnFirst
     */
    public javax.swing.JButton getBtnFirst() {
        return btnFirst;
    }

    /**
     * @param btnFirst the btnFirst to set
     */
    public void setBtnFirst(javax.swing.JButton btnFirst) {
        this.btnFirst = btnFirst;
    }

    /**
     * @return the btnLast
     */
    public javax.swing.JButton getBtnLast() {
        return btnLast;
    }

    /**
     * @param btnLast the btnLast to set
     */
    public void setBtnLast(javax.swing.JButton btnLast) {
        this.btnLast = btnLast;
    }

    /**
     * @return the btnNext
     */
    public javax.swing.JButton getBtnNext() {
        return btnNext;
    }

    /**
     * @param btnNext the btnNext to set
     */
    public void setBtnNext(javax.swing.JButton btnNext) {
        this.btnNext = btnNext;
    }

    /**
     * @return the txtPage
     */
    public javax.swing.JLabel getTxtPage() {
        return txtPage;
    }

    /**
     * @param txtPage the txtPage to set
     */
    public void setTxtPage(javax.swing.JLabel txtPage) {
        this.txtPage = txtPage;
    }

    /**
     * @return the btnSearch
     */
    public javax.swing.JButton getBtnSearch() {
        return btnSearch;
    }

    /**
     * @param btnSearch the btnSearch to set
     */
    public void setBtnSearch(javax.swing.JButton btnSearch) {
        this.btnSearch = btnSearch;
    }

    /**
     * @return the txtIssueDate
     */
    public org.jdesktop.swingx.JXDatePicker getTxtIssueDate() {
        return txtIssueDate;
    }

    /**
     * @param txtIssueDate the txtIssueDate to set
     */
    public void setTxtIssueDate(org.jdesktop.swingx.JXDatePicker txtIssueDate) {
        this.txtIssueDate = txtIssueDate;
    }

    /**
     * @return the txtDueDate
     */
    public org.jdesktop.swingx.JXDatePicker getTxtDueDate() {
        return txtDueDate;
    }

    /**
     * @param txtDueDate the txtDueDate to set
     */
    public void setTxtDueDate(org.jdesktop.swingx.JXDatePicker txtDueDate) {
        this.txtDueDate = txtDueDate;
    }

}
