/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PalSubject.java
 *
 * Created on Jan 3, 2011, 6:02:18 PM
 */

package view;

import javax.swing.ImageIcon;
import model.LibImages;

/**
 *
 * @author CuongNQ
 */
public class PalSubject extends javax.swing.JPanel {

    /** Creates new form PalSubject */
    public PalSubject() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tolbarSub = new javax.swing.JToolBar();
        btnAddSub = new javax.swing.JButton();
        separator5 = new javax.swing.JToolBar.Separator();
        btnEditSub = new javax.swing.JButton();
        btnViewSub = new javax.swing.JButton();
        btnDelSub = new javax.swing.JButton();
        separator6 = new javax.swing.JToolBar.Separator();
        btnSearchSub = new javax.swing.JButton();
        lblIDSub = new javax.swing.JLabel();
        lblNameSub = new javax.swing.JLabel();
        txtNameSub = new javax.swing.JTextField();
        txtIdSub = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        scrPanSub = new javax.swing.JScrollPane();
        tblSub = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnFirst = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtPage = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();

        setToolTipText("null");

        tolbarSub.setBorder(null);
        tolbarSub.setFloatable(false);
        tolbarSub.setBorderPainted(false);
        tolbarSub.setOpaque(false);

        btnAddSub.setIcon(new ImageIcon(getClass().getResource(LibImages.TASKBAR_ADD)));
        btnAddSub.setMnemonic('a');
        btnAddSub.setText("Add");
        btnAddSub.setBorderPainted(false);
        btnAddSub.setFocusable(false);
        btnAddSub.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddSub.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tolbarSub.add(btnAddSub);
        tolbarSub.add(separator5);

        btnEditSub.setIcon(new javax.swing.ImageIcon(getClass().getResource(LibImages.TASKBAR_EDIT)));
        btnEditSub.setMnemonic('e');
        btnEditSub.setText("Edit");
        btnEditSub.setBorderPainted(false);
        btnEditSub.setEnabled(false);
        btnEditSub.setFocusable(false);
        btnEditSub.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditSub.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tolbarSub.add(btnEditSub);

        btnViewSub.setIcon(new javax.swing.ImageIcon(getClass().getResource(LibImages.TASKBAR_VIEW)));
        btnViewSub.setMnemonic('v');
        btnViewSub.setText("View");
        btnViewSub.setBorderPainted(false);
        btnViewSub.setEnabled(false);
        btnViewSub.setFocusable(false);
        btnViewSub.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnViewSub.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tolbarSub.add(btnViewSub);

        btnDelSub.setIcon(new javax.swing.ImageIcon(getClass().getResource(LibImages.TASKBAR_DETELE)));
        btnDelSub.setMnemonic('d');
        btnDelSub.setText("Delete");
        btnDelSub.setBorderPainted(false);
        btnDelSub.setEnabled(false);
        btnDelSub.setFocusable(false);
        btnDelSub.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelSub.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tolbarSub.add(btnDelSub);
        tolbarSub.add(separator6);

        btnSearchSub.setIcon(new javax.swing.ImageIcon(getClass().getResource(LibImages.TASKBAR_SEARCH)));
        btnSearchSub.setMnemonic('s');
        btnSearchSub.setText("Search");
        btnSearchSub.setBorderPainted(false);
        btnSearchSub.setFocusable(false);
        btnSearchSub.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSearchSub.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tolbarSub.add(btnSearchSub);

        lblIDSub.setText("Subject ID:");

        lblNameSub.setText("Subject Name:");

        txtNameSub.setToolTipText("Subject's username");

        txtIdSub.setToolTipText("Subject's ID");

        jPanel1.setLayout(new java.awt.BorderLayout());

        tblSub.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scrPanSub.setViewportView(tblSub);

        jPanel1.add(scrPanSub, java.awt.BorderLayout.CENTER);

        btnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource(LibImages.TASKBAR_FIRST)));
        btnFirst.setBorderPainted(false);
        jPanel2.add(btnFirst);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource(LibImages.TASKBAR_BACK)));
        btnBack.setBorderPainted(false);
        jPanel2.add(btnBack);

        txtPage.setText("Pages");
        jPanel2.add(txtPage);

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource(LibImages.TASKBAR_NEXT)));
        btnNext.setBorderPainted(false);
        jPanel2.add(btnNext);

        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource(LibImages.TASKBAR_LAST)));
        btnLast.setBorderPainted(false);
        jPanel2.add(btnLast);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(tolbarSub, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblIDSub)
                    .add(lblNameSub))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(txtIdSub, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                    .add(txtNameSub, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)))
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, tolbarSub, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lblIDSub)
                            .add(txtIdSub, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(2, 2, 2)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lblNameSub)
                            .add(txtNameSub, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSub;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelSub;
    private javax.swing.JButton btnEditSub;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnSearchSub;
    private javax.swing.JButton btnViewSub;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblIDSub;
    private javax.swing.JLabel lblNameSub;
    private javax.swing.JScrollPane scrPanSub;
    private javax.swing.JToolBar.Separator separator5;
    private javax.swing.JToolBar.Separator separator6;
    private javax.swing.JTable tblSub;
    private javax.swing.JToolBar tolbarSub;
    private javax.swing.JTextField txtIdSub;
    private javax.swing.JTextField txtNameSub;
    private javax.swing.JLabel txtPage;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the btnAddSub
     */
    public javax.swing.JButton getBtnAddSub() {
        return btnAddSub;
    }

    /**
     * @param btnAddSub the btnAddSub to set
     */
    public void setBtnAddSub(javax.swing.JButton btnAddSub) {
        this.btnAddSub = btnAddSub;
    }

    /**
     * @return the btnDelSub
     */
    public javax.swing.JButton getBtnDelSub() {
        return btnDelSub;
    }

    /**
     * @param btnDelSub the btnDelSub to set
     */
    public void setBtnDelSub(javax.swing.JButton btnDelSub) {
        this.btnDelSub = btnDelSub;
    }

    /**
     * @return the btnEditSub
     */
    public javax.swing.JButton getBtnEditSub() {
        return btnEditSub;
    }

    /**
     * @param btnEditSub the btnEditSub to set
     */
    public void setBtnEditSub(javax.swing.JButton btnEditSub) {
        this.btnEditSub = btnEditSub;
    }

    /**
     * @return the btnSearchSub
     */
    public javax.swing.JButton getBtnSearchSub() {
        return btnSearchSub;
    }

    /**
     * @param btnSearchSub the btnSearchSub to set
     */
    public void setBtnSearchSub(javax.swing.JButton btnSearchSub) {
        this.btnSearchSub = btnSearchSub;
    }

    /**
     * @return the btnViewSub
     */
    public javax.swing.JButton getBtnViewSub() {
        return btnViewSub;
    }

    /**
     * @param btnViewSub the btnViewSub to set
     */
    public void setBtnViewSub(javax.swing.JButton btnViewSub) {
        this.btnViewSub = btnViewSub;
    }

    /**
     * @return the tblSub
     */
    public javax.swing.JTable getTblSub() {
        return tblSub;
    }

    /**
     * @param tblSub the tblSub to set
     */
    public void setTblSub(javax.swing.JTable tblSub) {
        this.tblSub = tblSub;
    }

    /**
     * @return the txtIdSub
     */
    public javax.swing.JTextField getTxtIdSub() {
        return txtIdSub;
    }

    /**
     * @param txtIdSub the txtIdSub to set
     */
    public void setTxtIdSub(javax.swing.JTextField txtIdSub) {
        this.txtIdSub = txtIdSub;
    }

    /**
     * @return the txtNameSub
     */
    public javax.swing.JTextField getTxtNameSub() {
        return txtNameSub;
    }

    /**
     * @param txtNameSub the txtNameSub to set
     */
    public void setTxtNameSub(javax.swing.JTextField txtNameSub) {
        this.txtNameSub = txtNameSub;
    }

    /**
     * @return the btnBack
     */
    public javax.swing.JButton getBtnBack() {
        return btnBack;
    }

    /**
     * @param btnBack the btnBack to set
     */
    public void setBtnBack(javax.swing.JButton btnBack) {
        this.btnBack = btnBack;
    }

    /**
     * @return the btnFirst
     */
    public javax.swing.JButton getBtnFirst() {
        return btnFirst;
    }

    /**
     * @param btnFirst the btnFirst to set
     */
    public void setBtnFirst(javax.swing.JButton btnFirst) {
        this.btnFirst = btnFirst;
    }

    /**
     * @return the btnLast
     */
    public javax.swing.JButton getBtnLast() {
        return btnLast;
    }

    /**
     * @param btnLast the btnLast to set
     */
    public void setBtnLast(javax.swing.JButton btnLast) {
        this.btnLast = btnLast;
    }

    /**
     * @return the btnNext
     */
    public javax.swing.JButton getBtnNext() {
        return btnNext;
    }

    /**
     * @param btnNext the btnNext to set
     */
    public void setBtnNext(javax.swing.JButton btnNext) {
        this.btnNext = btnNext;
    }

    /**
     * @return the txtPage
     */
    public javax.swing.JLabel getTxtPage() {
        return txtPage;
    }

    /**
     * @param txtPage the txtPage to set
     */
    public void setTxtPage(javax.swing.JLabel txtPage) {
        this.txtPage = txtPage;
    }

}
