/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SendAlertDialog.java
 *
 * Created on Jan 15, 2011, 4:24:46 PM
 */

package view;

import model.LibImages;

/**
 *
 * @author CuongNQ
 */
public class SendAlertDialog extends javax.swing.JDialog {

    /** Creates new form SendAlertDialog */
    public SendAlertDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTo = new javax.swing.JLabel();
        lblForm = new javax.swing.JLabel();
        lblSubject = new javax.swing.JLabel();
        lblContent = new javax.swing.JLabel();
        txtTo = new javax.swing.JTextField();
        txtForm = new javax.swing.JTextField();
        txtSubject = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtContent = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        btnSend = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTo.setText("To:");

        lblForm.setText("Form:");

        lblSubject.setText("Subject:");

        lblContent.setText("Content:");

        jScrollPane1.setViewportView(txtContent);

        btnSend.setText("Send");
        jPanel1.add(btnSend);

        btnClose.setText("Close");
        jPanel1.add(btnClose);

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(LibImages.LABEL_EMAIL)));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblSubject)
                    .add(lblForm)
                    .add(lblTo)
                    .add(lblContent))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 169, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(lblImage)
                                .add(37, 37, 37))))
                    .add(txtSubject, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                    .add(txtForm, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                    .add(txtTo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblTo)
                    .add(txtTo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtForm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblForm))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblSubject)
                    .add(txtSubject, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblContent)
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE))
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(lblImage)
                        .add(67, 67, 67)
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(28, 28, 28))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSend;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblContent;
    private javax.swing.JLabel lblForm;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JLabel lblTo;
    private javax.swing.JTextPane txtContent;
    private javax.swing.JTextField txtForm;
    private javax.swing.JTextField txtSubject;
    private javax.swing.JTextField txtTo;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the btnClose
     */
    public javax.swing.JButton getBtnClose() {
        return btnClose;
    }

    /**
     * @param btnClose the btnClose to set
     */
    public void setBtnClose(javax.swing.JButton btnClose) {
        this.btnClose = btnClose;
    }

    /**
     * @return the btnSend
     */
    public javax.swing.JButton getBtnSend() {
        return btnSend;
    }

    /**
     * @param btnSend the btnSend to set
     */
    public void setBtnSend(javax.swing.JButton btnSend) {
        this.btnSend = btnSend;
    }

    /**
     * @return the txtContent
     */
    public javax.swing.JTextPane getTxtContent() {
        return txtContent;
    }

    /**
     * @param txtContent the txtContent to set
     */
    public void setTxtContent(javax.swing.JTextPane txtContent) {
        this.txtContent = txtContent;
    }

    /**
     * @return the txtForm
     */
    public javax.swing.JTextField getTxtForm() {
        return txtForm;
    }

    /**
     * @param txtForm the txtForm to set
     */
    public void setTxtForm(javax.swing.JTextField txtForm) {
        this.txtForm = txtForm;
    }

    /**
     * @return the txtSubject
     */
    public javax.swing.JTextField getTxtSubject() {
        return txtSubject;
    }

    /**
     * @param txtSubject the txtSubject to set
     */
    public void setTxtSubject(javax.swing.JTextField txtSubject) {
        this.txtSubject = txtSubject;
    }

    /**
     * @return the txtTo
     */
    public javax.swing.JTextField getTxtTo() {
        return txtTo;
    }

    /**
     * @param txtTo the txtTo to set
     */
    public void setTxtTo(javax.swing.JTextField txtTo) {
        this.txtTo = txtTo;
    }

}
